### ISSUE TITLE
RDFa and JSON-LD are not equivalent

### ISSUE THREAD

**Issue by iherman** [w3c/microdata#78]
RDFa and JSON-LD are both serializations of RDF. What it means that, when converted to RDF, both conversion results should produce equivalent graphs.

However... this does not seem to be the case. At least the way I read it

* JSON-LD has a top level `items` property, which yields, in RDF one subject (a blank node, actually) which has a number of `<items> _:XYZ` pairs, where `_:XYZ` are blank nodes with the content coming from a specific `itemscope`
* RDFa yields a number `_:XYZ` triplets without any common subjects binding them together.

This can be easily solved. Either

* The JSON-LD structure uses a top level `@graph` construct which can be used to specify a number of more or less independent group of triples with common subjects
* The RDFa version is extended by an artificial HTML code providing the equivalent of the JSON-LD `items`

I am more in favour of the first approach to solve this, but the second one is also a solution.

(As an aside, the JSON-LD example is incomplete, there is no `@context`.)

Cc: @gkellogg

**Comment by gkellogg** [comment]
Ivan is correct, for the `items` property to not create a blank node, the context must include `"items": "@graph"`, or, the generation of the `items` element should simply be eliminated, and replaced with `"@graph"`, which is what I did in [my implementation](https://github.com/ruby-rdf/rdf-microdata/blob/develop/lib/rdf/microdata/jsonld_reader.rb).

My implementation produces the following output for the example in the spec:

```json
{
  "@graph": [
    {
      "@context": {
        "@vocab": "https://schema.org/"
      },
      "@type": [
        "https://schema.org/BlogPosting"
      ],
      "headline": [
        "Progress report"
      ],
      "url": [
        {
          "@id": "http://example.com?comments=0"
        }
      ],
      "comment": [
        {
          "@context": {
            "@vocab": "https://schema.org/"
          },
          "@type": [
            "https://schema.org/Comment"
          ],
          "url": [
            {
              "@id": "http://example.com#c1"
            }
          ],
          "creator": [
            {
              "@context": {
                "@vocab": "https://schema.org/"
              },
              "@type": [
                "https://schema.org/Person"
              ],
              "name": [
                "Greg"
              ]
            }
          ],
          "dateCreated": [
            "2013-08-29"
          ]
        }
      ],
      "datePublished": [
        "2013-08-29"
      ]
    }
  ]
}
```

**Comment by chaals** [comment]
It looks like the example was just copy-pasted from the plain JSON conversion, and is really wrong :(

So it looks like step 4 of the algorithm should say

> Add an entry to _result_ called "`@graph`" whose value is the array _items_.

@gkellogg you seem to have done the `@context` step differently, and instead of making it a top-level entry in _items_ added

```
@context : {
    @vocab :  _vocabulary-identifier_
}  
``` 

to each _item_.

* Does that matter in getting the JSON-LD right? (I **think** at first glance the answer is no)
* Would doing the existing step 5, but with `@vocab` set to the _vocabulary-identifier_ change the resulting graph? (Again, I **think** the answer is no)

Seem like we should also clarify that the algorithm is not normatively required to be followed exactly, but that a conversion should produce JSON-LD that represents the same RDF graph, probably at the beginning of the JSON-LD conversion section.

**Comment by gkellogg** [comment]
Setting `@context` at the top means that if the vocabulary changes along the way, you won't pick it up. Setting it for each item, while repetitions, does make sure that the object for each item is picked up if it happens to change.

I believe that setting `"@vocab": _vocabulary-identifier_` (when properly quoted) is don't what I do.

**Comment by chaals** [comment]
> Setting @context at the top means that if the vocabulary changes along the way, you won't pick it up. Setting it for each item, while repetitions, does make sure that the object for each item is picked up if it happens to change.

But in microdata, my first instinct is that it cannot change anyway, in which case this protection is unnecessary. (Wondering if I missed something)

> I believe that setting "@vocab": _vocabulary-identifier_ (when properly quoted) is don't what I do.

_vocabulary-identifier_ is (meant to be) the URL path for the (first) itemtype. Are you getting something different to use as a value? (I don't understand "don't" in the sentence above)

**Comment by gkellogg** [comment]
> But in microdata, my first instinct is that it cannot change anyway, in which case this protection is unnecessary. (Wondering if I missed something)

In section 4.3, the _vocabulary identifier_ is determined based on _itemtype_, which can certainly change when a new _itemscope_ is encountered. Otherwise, you couldn't use properties from different vocabularies. Certainly, the RDFa algorithm is written expecting that the _vocabulary identifier_ can change with each item, which is my read of 4.3 and 5.2:

> The item types determine the vocabulary identifier.

I'm not sure where you see that the _vocabulary-identifier_ is only associated with the first _itemtype_.

**Comment by iherman** [comment]
Looking at the example of @gkellogg's generation tells me that there is a need for a specific `@context` file for microdata to make the output simpler and more readable. Lines like 

```
     "url": [
        {
          "@id": "http://example.com?comments=0"
        }
      ],
```

could then disappear behind the smoke screen of a context. At present, without such a context file, the generated JSON-LD does not seem to be correct...

**Comment by iherman** [comment]
@chaals @gkellogg 

> > But in microdata, my first instinct is that it cannot change anyway, in which case this protection is unnecessary. (Wondering if I missed something)
>
> In section 4.3, the vocabulary identifier is determined based on itemtype, which can certainly change when a new itemscope is encountered.

That is correct, but I believe the comment of @chaals referred to the `@context`. While I agree that the vocabulary may change, I guess we can safely say that the `@context` will not...

**Comment by gkellogg** [comment]
For the vocabulary to track, and properties to be properly expanded, the `@context` must change with each item, at least for each item where the current vocabulary changes, otherwise, results will be quite different.

Consider a mixed use of DCMI and schema.org, if the context (and `@vocab`) is set for one, then items that use an `@itermtype` from the other will no longer come up as part of that vocabulary.

**Comment by iherman** [comment]
Ah, true. 

Would it be an over-complication in the document if the algorithm includes a check on whether `@context` and/or `@vocab` is necessary (as far as I can see a simple check on the DOM tree would be sufficient)?

**Comment by gkellogg** [comment]
Simplest, of course, is to just emit an `@context/@vocab` for each item, which doesn't require history. (Note that `@vocab` can only be used within `@context`). But, it might be done by passing `current-vocabulary` into the algorithm, and editing the `@context/@vocab` whenever the **vocabulary identifier** differs from that passed into the algorithm, and include it as part of step 7.2.

**Comment by iherman** [comment]
Exactly. I would propose to add that to the algorithm. Because we are generating a proper and, potentially, human readable serialization of RDF (as opposed to an abstract RDF Graph), I think such seemingly minor improvements would help acceptance and deployment.

**Comment by chaals** [comment]
Following discussion at TPAC, our proposal is to remove the JSON-LD conversion - it is just a convenience, and so long as you generate a minimal graph that is the same when converting to an RDF format it doesn't matter much which format you use...

And I apparently made fewer mistakes in creating the first draft RDFa conversion, so we will stick to that. It is also closer in the problem space it covers.
